
name: build-and-deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set timestamp
        run: echo "TIMESTAMP=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t princelinshiny/assessment:${{ env.TIMESTAMP }} .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER_NAME }}" --password-stdin

      - name: Push Docker image
        run: docker push princelinshiny/assessment:${{ env.TIMESTAMP }}

      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > $HOME/.kube/config
          
      - name: Test kubeconfig
          run: kubectl get nodes

      - name: Update Deployment with new image
        run: |
          kubectl set image deployment/wisecow-deployment \
          wisecow=princelinshiny/assessment:${{ env.TIMESTAMP }}
          kubectl rollout status deployment/wisecow-deployment


